# Picamera Legacy API Settings

["ALL Settings"]
options = ["Dpad for settings"]

[radius1x]
options = [25, 50, 75, 100, 125, 150, 175, 200]

[hairwidth1x]
options = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

[radius6x]
options = [200, 225, 250, 275, 300, 325, 350, 375, 400]

[hairwidth6x]
options = [10, 15, 20, 25, 30, 35, 40]

[radius10x]
options = [200, 225, 250, 275, 300, 325, 350, 375, 400, 450, 500, 550, 600]

[hairwidth10x]
options = [20, 25, 30, 35, 40, 45, 50, 55, 60]

[shotcam]
options = ["True", "False"]

[opacity]
# opacity setting
options = [0, 5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80, 85, 90, 95, 100]

[iso]
# ISO sensitivity
options = [0, 100, 200, 320, 400, 500, 640, 800]

[exposure_mode]
# Exposure modes
options = ["auto", "night", "nightpreview", "backlight", "spotlight", "sports", "snow", "beach", "verylong", "fixedfps", "antishake", "fireworks"]

[awb_mode]
# Auto White Balance modes
options = ["auto", "off", "sunlight", "cloudy", "shade", "tungsten", "fluorescent", "incandescent", "flash", "horizon"]

[brightness]
# Brightness level (0-100)
options = [0, 10, 20, 30, 40, 50, 60, 70, 80, 90, 100]

[contrast]
# Contrast level (-100 to 100)
options = [-50, -45, -40, -35, -30, -25, -20, -15, -10, -5, 0, 5, 10, 15, 20, 25, 30, 35, 40, 45, 50]

[saturation]
# Saturation level (-100 to 100)
options = [-50, -40, -30, -20, -10, 0, 10, 20, 30, 40, 50]

[sharpness]
# Sharpness level (-100 to 100)
options = [-100, -90, -80, -70, -60, -50, -40, -30, -20, -10, 0, 10, 20, 30, 40, 50, 60, 70, 80, 90, 100]

[effects]
# Image effects
options = ["none", "negative", "solarize", "sketch", "emboss", "blur", "saturation", "colorswap", "washedout", "posterise", "colorpoint", "colorbalance", "cartoon"]
